### ISSUE TITLE
Todo - urgent

### ISSUE THREAD

**Issue by mov51** [theAspenGrove/BlueMap-Sync#1]
- [ ] Check for jar response when refreshing render
- [ ] Add "render complete message"
- [ ] Move non-private configs to a separate config file
